---
name: Docker Image Magepack
on:
  schedule:
  - cron: "0 6 1 * *"
  push:
    paths:
    - images/.trigger
    - images/magepack/**
    branches:
    - main
jobs:
  magepack:
    name: Magepack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh "${BUILD_GROUP}"
      env:
        BUILD_GROUP: magepack
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        PUSH: "true"
