# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "Node â€¢ Docker Build"
on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/node/**
    branches:
      - main
jobs:
  build:
    name: "Build node"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - BUILD_TAG: "latest"
            IMAGE_TAG: "22"
          - BUILD_TAG: "22"
            IMAGE_TAG: "22"
          - BUILD_TAG: "20"
            IMAGE_TAG: "20"
          - BUILD_TAG: "18"
            IMAGE_TAG: "18"
          - BUILD_TAG: "16"
            IMAGE_TAG: "16"
          - BUILD_TAG: "14"
            IMAGE_TAG: "14"
          - BUILD_TAG: "12"
            IMAGE_TAG: "12"
          - BUILD_TAG: "10"
            IMAGE_TAG: "10"
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: mirror.gcr.io/tonistiigi/binfmt:latest

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - uses: supplypike/setup-bin@v4
        with:
          uri: https://github.com/hairyhenderson/gomplate/releases/latest/download/gomplate_linux-amd64
          name: gomplate
          version: latest

      - name: Generate Dockerfile
        run: gomplate -f images/node/tpl.Dockerfile -o images/node/Dockerfile
        env:
          IMAGE_TAG: ${{ matrix.IMAGE_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: images/node/context
          file: images/node/Dockerfile
          push: true
          platforms: "linux/amd64,linux/arm/v7,linux/arm64"
          tags: ${{ vars.DOCKER_REPO }}/node:${{ matrix.BUILD_TAG }}
          cache-from: type=registry,ref=${{ vars.DOCKER_REPO }}/node:${{ matrix.BUILD_TAG }}
          cache-to: type=inline
